### PR TITLE
simplify CI linting

### PR DESCRIPTION
**Pull request by forana**
This PR simplifies the linting action in a few ways:

1. No reason to restrict it to running on main or PRs that target main. Just run it on every push. It's fast.
2. ~No reason to run it on a schedule - the code's not going to change on its own.~
3. Switched from installing `miniconda` to just using `python` instead - we weren't actually using conda.

### CODE REVIEW

**Comment by jameslamb** [comment]
> No reason to run it on a schedule - the code's not going to change on its own.

@forana when I set this up, I did the scheduled thing because we're letting the linters float (and not pinning them). If a new version of `black` causes a test failure, I'd rather find that out on a Monday morning than in the middle of a period where I'm trying to get a release or other urgent change out.

**Comment by forana** [comment]
> > No reason to run it on a schedule - the code's not going to change on its own.
> 
> @forana when I set this up, I did the scheduled thing because we're letting the linters float (i.e. not pinning them). If a new version of `black` causes a test failure, I'd rather find that out on a Monday morning than in the middle of a period where I'm trying to get a release or other urgent change out.

mmm, reasonable - added back in `9c5fb96`

**Review by jameslamb — COMMENTED** [review]
looks fine to me, but I have a question.

What is the reason for this change? Is `actions/setup-python@v2` faster than `s-weigand/setup-conda@v1.0.3` or something?

**Comment by forana** [comment]
> looks fine to me, but I have a question.
> 
> What is the reason for this change? Is `actions/setup-python@v2` faster than `s-weigand/setup-conda@v1.0.3` or something?

Just noticed it when I was looking at the file - this isn't an urgent change and can be closed out if we decide we don't want it. It's a few seconds faster, but in general it feels like a good idea to rely on third-party actions only as much as we need to - in this case, a github-owned alternative was available.

**Comment by jameslamb** [comment]
> in this case, a github-owned alternative was available.

Ok that was the missing piece of context...that this is GitHub-managed instead of by some random person. Thanks! I'm fine with this change, then.

**Review by jameslamb — APPROVED** [review]

**Pull request merged**
