### PR TITLE
Update dask-saturn pin to 0.4.0

### PR DESCRIPTION
**Pull request by jsignell**
Rebuilding images to update dask-saturn pin

### CODE REVIEW

**Review by bhperry — APPROVED** [review]
LGTM

**Comment by jsignell** [comment]
@forana should I change the base branch to 2021.09.20? Those images already have dask-saturn 0.4.0, this just makes it explicit.

**Comment by bhperry** [comment]
It looks like the 2021.08.16 branch requires dask-saturn 0.4.0, so would be good to update images there

**Comment by jsignell** [comment]
> It looks like the 2021.08.16 branch requires dask-saturn 0.4.0 for prefect flows, so would be good to update images there

Yeah but it's just for prefect-cloud-flows, so it's not a huge deal if we tell people to update dask-saturn in their start scripts.

**Comment by bhperry** [comment]
true

**Pull request merged**
