### PR TITLE
[CU-fav17w] saturnbase-gpu should not register jupyter-server-proxy, only jupyter_server_proxy is valid

### PR DESCRIPTION
**Pull request by hhuuggoo**

### CODE REVIEW

**Comment by hhuuggoo** [comment]
Task linked: [CU-fav17w saturnbase-gpu should not register jupyter-server-proxy, only jupyter_server_proxy is valid](https://app.clickup.com/t/fav17w)

**Comment by jsignell** [comment]
Whoops - accidental close.

**Comment by jsignell** [comment]
You want this off main not release?

**Comment by hhuuggoo** [comment]
> You want this off main not release?

yea it's not breaking anything, I guess jupyter-server-proxy still works even if you don't enable it

**Pull request merged**
